global:
  message: welcome to Order service dev environment
message: Hello from Order Dev
spring:
  datasource:
    url: jdbc:h2:mem:demo_order_master_dev
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto:create
    show-sql: true
